# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/patching.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14proto/patching.proto")\n\rHeldInputJack\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t"U\n\x0eHeldOutputJack\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05\x63olor\x18\x03 \x01(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05"X\n\nLocalState\x12#\n\x0bheld_inputs\x18\x01 \x03(\x0b\x32\x0e.HeldInputJack\x12%\n\x0cheld_outputs\x18\x02 \x03(\x0b\x32\x0f.HeldOutputJack"i\n\x0fPatchConnection\x12\x12\n\ninput_uuid\x18\x01 \x01(\t\x12\x15\n\rinput_jack_id\x18\x02 \x01(\t\x12\x13\n\x0boutput_uuid\x18\x03 \x01(\t\x12\x16\n\x0eoutput_jack_id\x18\x04 \x01(\t"8\n\x06Update\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12 \n\x0blocal_state\x18\x02 \x01(\x0b\x32\x0b.LocalState"\x1f\n\x0fSnapshotRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t"Q\n\x10SnapshotResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12!\n\x07patched\x18\x03 \x03(\x0b\x32\x10.PatchConnection":\n\tSetPreset\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x1f\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x11.SnapshotResponse"c\n\x0cSetInputJack\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x1f\n\x06source\x18\x02 \x01(\x0b\x32\x0f.HeldOutputJack\x12$\n\nconnection\x18\x03 \x01(\x0b\x32\x10.PatchConnection"\x14\n\x04Halt\x12\x0c\n\x04uuid\x18\x01 \x01(\t"\xf3\x01\n\tDirective\x12\x19\n\x06update\x18\x01 \x01(\x0b\x32\x07.UpdateH\x00\x12,\n\x10snapshot_request\x18\x02 \x01(\x0b\x32\x10.SnapshotRequestH\x00\x12.\n\x11snapshot_response\x18\x03 \x01(\x0b\x32\x11.SnapshotResponseH\x00\x12 \n\nset_preset\x18\x04 \x01(\x0b\x32\n.SetPresetH\x00\x12\'\n\x0eset_input_jack\x18\x05 \x01(\x0b\x32\r.SetInputJackH\x00\x12\x15\n\x04halt\x18\x06 \x01(\x0b\x32\x05.HaltH\x00\x42\x0b\n\tdirectiveb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.patching_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _HELDINPUTJACK._serialized_start = 24
    _HELDINPUTJACK._serialized_end = 65
    _HELDOUTPUTJACK._serialized_start = 67
    _HELDOUTPUTJACK._serialized_end = 152
    _LOCALSTATE._serialized_start = 154
    _LOCALSTATE._serialized_end = 242
    _PATCHCONNECTION._serialized_start = 244
    _PATCHCONNECTION._serialized_end = 349
    _UPDATE._serialized_start = 351
    _UPDATE._serialized_end = 407
    _SNAPSHOTREQUEST._serialized_start = 409
    _SNAPSHOTREQUEST._serialized_end = 440
    _SNAPSHOTRESPONSE._serialized_start = 442
    _SNAPSHOTRESPONSE._serialized_end = 523
    _SETPRESET._serialized_start = 525
    _SETPRESET._serialized_end = 583
    _SETINPUTJACK._serialized_start = 585
    _SETINPUTJACK._serialized_end = 684
    _HALT._serialized_start = 686
    _HALT._serialized_end = 706
    _DIRECTIVE._serialized_start = 709
    _DIRECTIVE._serialized_end = 952
# @@protoc_insertion_point(module_scope)
